// <auto-generated />
using System;
using CinemaBooking.DbLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaBooking.DbLayer.Migrations
{
    [DbContext(typeof(CinemaBookingContext))]
    [Migration("20261002083712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("BookingTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("BookingTime");

                    b.Property<string>("ReservedSeatIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ReservedSeatIds");

                    b.Property<long>("ShowTimeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ShowTimeId");

                    b.HasKey("Id");

                    b.HasIndex("ShowTimeId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Movie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Category");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.ToTable("Movie", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Seat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Number");

                    b.Property<long?>("ReservationTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReservationTime");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Row");

                    b.Property<long>("ShowTimeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ShowTimeId");

                    b.Property<short>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("ShowTimeId");

                    b.ToTable("Seat", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Showtime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuditoriumId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AuditoriumId");

                    b.Property<long>("MovieId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MovieId");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtime", (string)null);
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Showtime", null)
                        .WithMany()
                        .HasForeignKey("ShowTimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Seat", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Showtime", null)
                        .WithMany("Seats")
                        .HasForeignKey("ShowTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Showtime", b =>
                {
                    b.HasOne("CinemaBooking.Domain.Entities.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBooking.Domain.Entities.Showtime", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
